#!/bin/bash

CLASSPATH="./:oadr2-app/target/oadr2-app-0.1.0.jar:./oadr2-app/target/lib/oadr2-xmpp-0.1.0.jar:./oadr2-app/target/lib/oadr2-model-0.1.0.jar:./oadr2-app/target/lib/jaxb2-basics-runtime-0.6.1.jar:./oadr2-app/target/lib/jaxb2-fluent-api-3.0.jar:./oadr2-app/target/lib/persistence-api-1.0.2.jar:./oadr2-app/target/lib/hyperjaxb3-ejb-runtime-0.5.6.jar:./oadr2-app/target/lib/commons-lang-2.2.jar:./oadr2-app/target/lib/smack-3.2.1.jar:./oadr2-app/target/lib/smackx-3.2.1.jar:./oadr2-app/target/lib/jaxb-impl-2.2.5.1.jar:./oadr2-app/target/lib/slf4j-log4j12-1.5.8.jar:./oadr2-app/target/lib/slf4j-api-1.5.8.jar:./oadr2-app/target/lib/log4j-1.2.16.jar"
export CLASSPATH
java org.enernoc.open.oadr2.xmpp.OadrApp
